config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :email_addresses, except: [:index, :show]

  resources :phone_numbers, except: [:index, :show]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'

  root to: 'site#index'

  get "/login" => redirect("/auth/twitter"), as: :login

  delete "/logout" => "sessions#destroy", as: :logout

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :contact, polymorphic: true
  validates :number, :contact_id, presence: true

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :contact_id, :contact_type)
    end
end

app/views/phone_numbers/_form.html.haml
= form_for(@phone_number) do |f|
  - if @phone_number.errors.any?
    #error_explanation
      %h2
        = pluralize(@phone_number.errors.count, "error")
        prohibited this phone_number from being saved:
      %ul
        - @phone_number.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :number
    %br/
    = f.text_field :number
  .field
    = f.hidden_field :contact_id
    = f.hidden_field :contact_type
  .actions
    = f.submit

app/views/phone_numbers/_phone_numbers.html.haml
%ul
  - phone_numbers.each do |phone|
    %li
      = phone.number
      = link_to('edit', edit_phone_number_path(phone))
      | #{link_to('delete', phone, method: :delete)}

app/views/phone_numbers/edit.html.haml
%h1= "Editing Phone Number for #{@phone_number.contact}"
= render 'form'
= link_to 'Show', @phone_number
|
\#{link_to 'Back', phone_numbers_path}

app/views/phone_numbers/new.html.haml
%h1= "New Phone Number for #{@phone_number.contact}"
= render 'form'
= link_to 'Back', phone_numbers_path