config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :email_addresses, except: [:index, :show]

  resources :phone_numbers, except: [:index, :show]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'

  root to: 'site#index'

  get "/login" => redirect("/auth/twitter"), as: :login

  delete "/logout" => "sessions#destroy", as: :logout

end

app/models/company.rb
class Company < ActiveRecord::Base
  include Contact
  belongs_to :user
  validates :name, presence: true

  def to_s
    name
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :lookup_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user = current_user
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private

    def lookup_company
      @company = current_user.companies.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/views/companies/_form.html.haml
= form_for(@company) do |f|
  - if @company.errors.any?
    #error_explanation
      %h2
        = pluralize(@company.errors.count, "error")
        prohibited this company from being saved:
      %ul
        - @company.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/companies/edit.html.haml
%h1
  Editing #{@company.name}
= render 'form'
%ul.actions
  %li= link_to 'Show', @company
  %li= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %thead
    %tr
      %th Name
      %th{colspan: "3"}
    
  %tbody
  - @companies.each do |company| 
    %tr
      %td= company.name 
      %td
        %ul.actions
          %li= link_to 'Show', company 
          %li= link_to 'Edit', edit_company_path(company) 
          %li= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } 
          
        
%br

= link_to 'New Company', new_company_path, id: 'new_company'

app/views/companies/new.html.haml
%h1 New company
= render 'form'
= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice
.company
  %h1= @company.name
  = render 'phone_numbers/phone_numbers', phone_numbers: @company.phone_numbers
  = render 'email_addresses/email_addresses', email_addresses: @company.email_addresses
  %ul.actions
    %li= link_to 'Add phone number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company')
    %li= link_to 'Add email address', new_email_address_path(contact_id: @company.id, contact_type: 'Company')
    %li= link_to 'Edit', edit_company_path(@company)
    %li= link_to 'Back', companies_path