config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :email_addresses, except: [:index, :show]

  resources :phone_numbers, except: [:index, :show]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'

  root to: 'site#index'

  get "/login" => redirect("/auth/twitter"), as: :login

  delete "/logout" => "sessions#destroy", as: :logout

end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  # GET /email_addresses/new
  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /email_addresses/1/edit
  def edit
  end

  # POST /email_addresses
  # POST /email_addresses.json
  def create
    @email_address = EmailAddress.new(email_address_params)

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render :show, status: :created, location: @email_address }
      else
        format.html { render :new }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_addresses/1
  # PATCH/PUT /email_addresses/1.json
  def update
    respond_to do |format|
      if @email_address.update(email_address_params)
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_address }
      else
        format.html { render :edit }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.json
  def destroy
    @email_address.destroy
    respond_to do |format|
      format.html { redirect_to @email_address.contact, notice: 'Email address was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def email_address_params
      params.require(:email_address).permit(:address, :contact_id, :contact_type)
    end
end

app/views/email_addresses/_email_addresses.html.haml
%ul
  - email_addresses.each do |email|
    %li
      = email.address
      = link_to('edit', edit_email_address_path(email))
      | #{link_to('delete', email, method: :delete)}

app/views/email_addresses/_form.html.haml
= form_for(@email_address) do |f|
  - if @email_address.errors.any?
    #error_explanation
      %h2
        = pluralize(@email_address.errors.count, "error")
        prohibited this email_address from being saved:
      %ul
        - @email_address.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :address
    %br/
    = f.text_field :address
  .field
    = f.hidden_field :contact_id
    = f.hidden_field :contact_type
  .actions
    = f.submit

app/views/email_addresses/edit.html.haml
%h1= "Editing Email for #{@email_address.contact}"
= render 'form'
= link_to 'Show', @email_address
|
\#{link_to 'Back', email_addresses_path}

app/views/email_addresses/new.html.haml
%h1= "New Email Address for #{@email_address.contact}"
= render 'form'
= link_to 'Back', email_addresses_path